# Each link needs a unique name. We recommend prefixing links with the name of
# your module. A links.menu.yml file can contain any number of link definitions.
ajinkya_config_api.weather:
  title: Weather
  description: Check this week's weather.
  menu_name: main
  # From ajinkya_config_api.routing.yml.
  route_name: ajinkya_config_api.weather_page

ajinkya_config_api.settings:
  title: Ajinkya config api Settings
  parent: system.admin_config_system
  route_name: ajinkya_config_api.settings
  weight: 10