<?php

/**
 * @file
 * Primary module hooks for omkar_entityapi module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function omkar_entityapi_theme(): array {
  return [
    'omkar_entityapi_profile' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for profile templates.
 *
 * Default template: omkar-entityapi-profile.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the profile information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_omkar_entityapi_profile(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function omkar_entityapi_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish profiles.
      $storage = \Drupal::entityTypeManager()->getStorage('omkar_entityapi_profile');
      $omkar_entityapi_profile_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($omkar_entityapi_profile_ids) as $omkar_entityapi_profile) {
        $omkar_entityapi_profile->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize profiles.
      $storage = \Drupal::entityTypeManager()->getStorage('omkar_entityapi_profile');
      $omkar_entityapi_profile_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($omkar_entityapi_profile_ids) as $omkar_entityapi_profile) {
        $omkar_entityapi_profile->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function omkar_entityapi_user_predelete(UserInterface $account): void {
  // Delete profiles that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('omkar_entityapi_profile');
  $omkar_entityapi_profile_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($omkar_entityapi_profile_ids)
  );
}
